import DashboardLayout from "@/components/DashboardLayout";
import { getCurrUser } from "@/server-actions/get-curr-user";
import "@/styles/globals.css";
import type { Metadata } from "next";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function PageLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = await getCurrUser();

  if (!user?.data?.user) {
    redirect("/");
  }

  return <DashboardLayout>{children}</DashboardLayout>;
}
