import LayoutHeader from "@/components/LayoutHeader";
import "@/styles/globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function PageLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      <LayoutHeader />
      <div className="pt-[50px]">{children}</div>
    </div>
  );
}
